### ISSUE TITLE
allow simple dot notation in alias?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/lazy-cache#4]
not using `set-value` or something, but some more basic and simple.

**Comment by jonschlinkert** [comment]
I want to do this as well, but IMHO we should hold off on it until the community is a little better educated on what lazy-caching is and how it works. Some devs already (mistakenly) think this module is doing magic, so anything we add to this lib will make it seem more magical.

**Comment by jonschlinkert** [comment]
but let's keep this open and maybe implement when lazy-cache hits 50-100m downloads or some number where we can more easily make a case: "We've had X million downloads an X issues". idk, just thinking out loud

**Comment by doowb** [comment]
You can also implement this in your library for the specific case that you want to use...

> something.js

``` js
var something = require('lazy-cache')(require);
something('foo');
something('bar');
something('baz');

module.exports = something;
```

> utils.js

``` js
var utils = require('lazy-cache')(require);

utils('./something', 'something');
module.exports = utils;
```

> index.js

``` js
var utils = require('./utils');
utils.something.foo('blah');
```

So, after typing that out, I can see how the dot notation can be useful in the alias.

**Comment by tunnckoCore** [comment]
> So, after typing that out, I can see how the dot notation can be useful in the alias.

Indeed. I can do it, but don't want to create whole new file, even more when I need dot in only 2 aliases.

And I think this also will work?

``` js
var utils = require('lazy-cache')(require);
var fn = require
require = utils

require('foo')
require('bar')

utils.plugins = {}
utils.plugins.fooBar = require('qux-fez')

require = fn
module.exports = utils
```

it intentionally is before `require = fn`, is it needed?

and instead doing all this we will just be able to do it this way

``` js
var utils = require('lazy-cache')(require)
var fn = require
require = utils

require('isarray', 'isArray')
require('isobject', 'isObject')
require('limon-prev-next', 'plugins.prevNext')

require = fn
module.exports = utils
```

**Comment by jonschlinkert** [comment]
I'm convinced :)

[this](https://github.com/jonschlinkert/lazy-cache/pull/5/commits/45f0b44fa10dbcab5799342958ed367f11b611de#diff-1dd241c4cd3fd1dd89c570cee98b79ddR130) would be really nice to do
